[project]
name = "python-pix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Caio Carvalho", email = "caiocarvalho.py@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
python-pix = "python_pix:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]
